Models/Proveedore.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace EntreEspeciesNuevo.Models;

public partial class Proveedore
{
    public int IdProveedor { get; set; }
    [Required(ErrorMessage = "El Nit es Obligatorio*")]
    [Range(1000000, 999999999999999, ErrorMessage = "El Nit debe tener entre 7 y 15 dígitos")]
    public int? NitProveedor { get; set; }
    [Required(ErrorMessage = "El Nombre es Obligatorio*")]
    [StringLength(50, MinimumLength = 3, ErrorMessage = "El Nombre debe tener entre 3 y 50 caracteres")]
    public string? NomProveedor { get; set; }
    [Required(ErrorMessage = "El Correo es Obligatorio*")]
    [RegularExpression(@"^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$", ErrorMessage = "El Correo no contiene un formato válido")]
    public string? Correo { get; set; }
    [Required(ErrorMessage = "El Telefono es Obligatorio*")]
    [Range(100000, 999999999999999, ErrorMessage = "El Telefono debe tener entre 6 y 15 dígitos")]
    public string? Telefono { get; set; }

    [Required(ErrorMessage = "La Dirección es Obligatoria*")]
    [StringLength(100, MinimumLength = 4, ErrorMessage = "La Dirección debe tener entre 4 y 100 caracteres")]
    public string? Direccion { get; set; }
    [Required(ErrorMessage = "El Nombre de Contacto es Obligatorio*")]
    [StringLength(50, MinimumLength = 3, ErrorMessage = "El Nombre debe tener entre 3 y 50 caracteres")]
    public string? contacto { get; set; }

    public virtual ICollection<Compra> Compras { get; set; } = new List<Compra>();
}

Controllers/ProveedoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EntreEspeciesNuevo.Models;

namespace EntreEspeciesNuevo.Controllers
{
    public class ProveedoresController : Controller
    {
        private readonly EntreespeciessqlContext _context;

        public ProveedoresController(EntreespeciessqlContext context)
        {
            _context = context;
        }

        // GET: Proveedores
        public async Task<IActionResult> Index()
        {
            bool RegistrarProveedores = RegistrarProveedor().Result;
            ViewBag.RegistrarProveedores = RegistrarProveedores;
            bool ActualizarProveedores = ActualizarProveedor().Result;
            ViewBag.ActualizarProveedores = ActualizarProveedores;
            bool EliminarProveedores = EliminarProveedor().Result;
            ViewBag.EliminarProveedores = EliminarProveedores;
            bool VerProveedores = VerProveedor().Result;
            ViewBag.VerProveedores = VerProveedores;
            return _context.Proveedores != null ? 
                          View(await _context.Proveedores.ToListAsync()) :
                          Problem("Entity set 'EntreespeciessqlContext.Proveedores'  is null.");
        }
        public async Task<bool> RegistrarProveedor()
        {
            var username = User.Identity.Name;
            var usuario = await _context.Usuarios.FirstOrDefaultAsync(u => u.Nombre == username);
            if (usuario == null)
            {
                return false;
            }
            var configuracion = await _context.Configuracions
                .Where(c => c.IdRol == usuario.IdRol && c.IdPermiso == 29)
                .FirstOrDefaultAsync();
            return configuracion != null;
        }

        public async Task<bool> VerProveedor()
        {
            var username = User.Identity.Name;
            var usuario = await _context.Usuarios.FirstOrDefaultAsync(u => u.Nombre == username);
            if (usuario == null)
            {
                return false;
            }
            var configuracion = await _context.Configuracions
                .Where(c => c.IdRol == usuario.IdRol && c.IdPermiso == 28)
                .FirstOrDefaultAsync();
            return configuracion != null;
        }
        public async Task<bool> ActualizarProveedor()
        {
            var username = User.Identity.Name;
            var usuario = await _context.Usuarios.FirstOrDefaultAsync(u => u.Nombre == username);
            if (usuario == null)
            {
                return false;
            }
            var configuracion = await _context.Configuracions
                .Where(c => c.IdRol == usuario.IdRol && c.IdPermiso == 30)
                .FirstOrDefaultAsync();
            return configuracion != null;
        }
        public async Task<bool> EliminarProveedor()
        {
            var username = User.Identity.Name;
            var usuario = await _context.Usuarios.FirstOrDefaultAsync(u => u.Nombre == username);
            if (usuario == null)
            {
                return false;
            }
            var configuracion = await _context.Configuracions
                .Where(c => c.IdRol == usuario.IdRol && c.IdPermiso == 31)
                .FirstOrDefaultAsync();
            return configuracion != null;
        }
        // GET: Proveedores/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Proveedores == null)
            {
                return NotFound();
            }

            var proveedore = await _context.Proveedores
                .FirstOrDefaultAsync(m => m.IdProveedor == id);
            if (proveedore == null)
            {
                return NotFound();
            }

            return Json(proveedore);
        }

        // GET: Proveedores/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Proveedores/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdProveedor,NitProveedor,NomProveedor,Correo,Telefono,Direccion,contacto")] Proveedore proveedore)
        {
            // Verificar si ya existe un cliente con el mismo número de documento
            if (_context.Proveedores.Any(p => p.NitProveedor == proveedore.NitProveedor))
            {
                ModelState.AddModelError("NitProveedor", "Ya existe un proveedor con este número de nit.");
                return View(proveedore);
            }
            if (ModelState.IsValid)
            {
                _context.Add(proveedore);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(proveedore);
        }

        // GET: Proveedores/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Proveedores == null)
            {
                return NotFound();
            }

            var proveedore = await _context.Proveedores.FindAsync(id);
            if (proveedore == null)
            {
                return NotFound();
            }
            return View(proveedore);
        }

        // POST: Proveedores/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdProveedor,NitProveedor,NomProveedor,Correo,Telefono,Direccion,contacto")] Proveedore proveedore)
        {
            if (id != proveedore.IdProveedor)
            {
                return NotFound();
            }

            // Verificar si ya existe un proveedor con el mismo número de documento y diferente ID
            if (_context.Proveedores.Any(p => p.NitProveedor == proveedore.NitProveedor && p.IdProveedor != id))
            {
                ModelState.AddModelError("NitProveedor", "Ya existe un proveedor con este número de nit.");
                return View(proveedore);
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(proveedore);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProveedoreExists(proveedore.IdProveedor))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            return View(proveedore);
        }



        // GET: Proveedores/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Proveedores == null)
            {
                return NotFound();
            }

            var proveedore = await _context.Proveedores
                .FirstOrDefaultAsync(m => m.IdProveedor == id);
            if (proveedore == null)
            {
                return NotFound();
            }

            return View(proveedore);
        }

        // POST: Proveedores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Proveedores == null)
            {
                return Problem("Entity set 'EntreespeciessqlContext.Proveedores'  is null.");
            }
            var proveedore = await _context.Proveedores.FindAsync(id);
            if (proveedore != null)
            {
                _context.Proveedores.Remove(proveedore);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProveedoreExists(int id)
        {
          return (_context.Proveedores?.Any(e => e.IdProveedor == id)).GetValueOrDefault();
        }
    }
}

Views/Proveedores/Create.cshtml
@model EntreEspeciesNuevo.Models.Proveedore

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<head>
    <link rel="stylesheet" href="~/css/form.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-switch@3.3.4/dist/css/bootstrap3/bootstrap-switch.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400;700&display=swap">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Anta&family=Libre+Baskerville:ital,wght@0,400;0,700;1,400&display=swap" rel="stylesheet">
</head>

<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card rounded">
            <div class="card-body">
                <center> <h4 class="card-title" style="font-family: Arial, sans-serif;">Crear Proveedor</h4></center>
                <hr />
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group row">
                    <div class="col"
                        <label asp-for="NitProveedor" class="control-label">Nit del Proveedor:</label>
                        <input asp-for="NitProveedor" class="form-control" />
                        <span asp-validation-for="NitProveedor" class="text-danger"></span>
                    </div>

                    <div class="col">
                        <label asp-for="NomProveedor" class="control-label">Razón social:</label>
                        <input asp-for="NomProveedor" class="form-control" />
                        <span asp-validation-for="NomProveedor" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group">
                    <label asp-for="Correo" class="control-label">Correo:</label>
                    <input asp-for="Correo" class="form-control" />
                    <span asp-validation-for="Correo" class="text-danger"></span>
                </div>

                <div class="form-group row">
                    <div class="col"
                        <label asp-for="Telefono" class="control-label">Teléfono:</label>
                        <input asp-for="Telefono" class="form-control" />
                        <span asp-validation-for="Telefono" class="text-danger"></span>
                    </div>

                    <div class="col">
                        <label asp-for="Direccion" class="control-label">Dirección:</label>
                        <input asp-for="Direccion" class="form-control" />
                        <span asp-validation-for="Direccion" class="text-danger"></span>
                    </div>
                </div>
                    <div class="form-group">
                        <label asp-for="contacto" class="control-label">Nombre de Contacto:</label>
                        <input asp-for="contacto" class="form-control" />
                        <span asp-validation-for="contacto" class="text-danger"></span>
                    </div>
            
                <div class="form-group text-center">
                    <input type="submit" value="Crear" class="btn btn-primary" />
                    <button type="button" onclick="window.location.href='@Url.Action("Index")'" class="btn btn-secondary btn-gray">Cancelar</button>
                </div>
               
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");


    }
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const form = document.querySelector('form');
            form.addEventListener('submit', function (event) {
                let isValid = true;

                // Validar el campo NitProveedor
                const nitProveedorInput = document.getElementById('NitProveedor');
                const nitProveedorValue = nitProveedorInput.value.trim();
                if (nitProveedorValue === '') {
                    showError('Por favor, ingrese el Nit del proveedor.');
                    isValid = false;
                }

                // Validar el campo NomProveedor
                const nomProveedorInput = document.getElementById('NomProveedor');
                const nomProveedorValue = nomProveedorInput.value.trim();
                if (nomProveedorValue === '') {
                    showError('Por favor, ingrese el Nombre del proveedor.');
                    isValid = false;
                }

                // Validar el campo Correo
                const correoInput = document.getElementById('Correo');
                const correoValue = correoInput.value.trim();
                if (correoValue === '') {
                    showError('Por favor, ingrese el Correo del proveedor.');
                    isValid = false;
                }

                // Validar el campo Telefono
                const telefonoInput = document.getElementById('Telefono');
                const telefonoValue = telefonoInput.value.trim();
                if (telefonoValue === '') {
                    showError('Por favor, ingrese el Teléfono del proveedor.');
                    isValid = false;
                }
                    const contactoInput = document.getElementById('contacto');
                    const contactoValue = contactoInput.value.trim();
                    if (contactoValue === '') {
                        showError('Por favor, ingrese el un contacto.');
                        isValid = false;
                    }


                // Validar el campo Direccion
                const direccionInput = document.getElementById('Direccion');
                const direccionValue = direccionInput.value.trim();
                if (direccionValue === '') {
                    showError('Por favor, ingrese la Dirección del proveedor.');
                    isValid = false;
                }

                if (!isValid) {
                    event.preventDefault(); // Evitar el envío del formulario si no es válido
                }
                else{
                    Swal.fire({
                        icon: 'success',
                        title: 'Éxito',
                        text: 'El proveedor se ha creado exitosamente.',
                        timer: 7000
                    });
                }
            });

            function showError(message) {
                Swal.fire({
                    icon: 'error',
                    title: 'Error',
                    text: message
                });
            }
        });
    </script>
}

Views/Proveedores/Delete.cshtml
@model EntreEspeciesNuevo.Models.Proveedore

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Proveedore</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NitProveedor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NitProveedor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NomProveedor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NomProveedor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Correo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Correo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefono)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Direccion)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdProveedor" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Proveedores/Details.cshtml
@model EntreEspeciesNuevo.Models.Proveedore

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Proveedore</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NitProveedor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NitProveedor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NomProveedor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NomProveedor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Correo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Correo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefono)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Direccion)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.IdProveedor">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Proveedores/Index.cshtml
@model IEnumerable<EntreEspeciesNuevo.Models.Proveedore>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{
    var RegistrarProveedores = ViewBag.RegistrarProveedores;
    var ActualizarProveedores = ViewBag.ActualizarProveedores;
    var EliminarProveedores = ViewBag.EliminarProveedores;
    var VerProveedores = ViewBag.VerProveedores;
}
@if (VerProveedores)
{
    <head>
        <link rel="stylesheet" href="~/css/site.css" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-switch@3.3.4/dist/css/bootstrap3/bootstrap-switch.min.css" rel="stylesheet">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400;700&display=swap">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Anta&family=Libre+Baskerville:ital,wght@0,400;0,700;1,400&display=swap" rel="stylesheet">
    </head>

    <div class="d-flex justify-content-between align-items-center">
        <h1>Proveedores</h1>
        @if (RegistrarProveedores)
        {
            <p>
                <a class="btn btn-primary" asp-action="Create" style="margin-right: 20px;">Crear Proveedor</a>
            </p>
        }
    </div>

    <div class="table-container">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Nit del Proveedor
                    </th>
                    <th>
                        Razón Social
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Correo)
                    </th>
                    <th>
                        Teléfono
                    </th>
                    <th>
                        Dirección
                    </th>
                    <th>
                        Contacto
                    </th>
                    <th>
                        Acciones
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.NitProveedor)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.NomProveedor)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Correo)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Telefono)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Direccion)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.contacto)
                        </td>
                        <td>
                            @if (ActualizarProveedores)
                            {
                                <a class="btn btn-primary" asp-action="Edit" asp-route-id="@item.IdProveedor">Editar</a>
                            }
                            @* @if (EliminarProveedores)
                    {
                    <a class="btn btn-danger btn-sm" asp-action="Delete" asp-route-id="@item.IdProveedor">Cambio de Estado</a>
                    } *@

                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

    <div class="modal fade" id="detalleModal" tabindex="-1" role="dialog" aria-labelledby="detalleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="detalleModalLabel">Detalles de la Categoría</h5>
                </div>
                <div class="modal-body">
                    <!-- Aquí puedes mostrar la información detallada de la categoría -->
                    <div id="detalleContent"></div>
                </div>
                <div class="modal-footer mt-auto">
                    <button type="button" class="btn btn-secondary" id="closeModalBtn" data-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>
}
@section Scripts {
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.css">
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.js"></script>

    <script>
        $(document).ready(function () {
            $('.table').DataTable({
                "language": {
                    "sProcessing": "Procesando...",
                    "sLengthMenu": "Mostrar _MENU_ registros",
                    "sZeroRecords": "No se encontraron resultados",
                    "sEmptyTable": "Ningún dato disponible en esta tabla",
                    "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                    "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                    "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                    "sInfoPostFix": "",
                    "sSearch": "Buscar:",
                    "sUrl": "",
                    "sInfoThousands": ",",
                    "sLoadingRecords": "Cargando...",
                    "oPaginate": {
                        "sFirst": "Primero",
                        "sLast": "Último",
                        "sNext": "Siguiente",
                        "sPrevious": "Anterior"
                    },
                    "oAria": {
                        "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                        "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                    }
                },
                "lengthMenu": [4, 6, 10, 15],
                "pageLength": 10, // Número predeterminado de elementos por página
                "search": {
                    "search": "",
                    "searchPlaceholder": "Buscar...",
                },
                "dom": '<"d-flex justify-content-between align-items-center"lf>t<"d-flex justify-content-between align-items-center"ip>',
                "initComplete": function (settings, json) {
                    $('.dataTables_filter input[type="search"]').css({ 'border-radius': '5px', 'padding-left': '10px' });
                }
            });
        });
    </script>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const detalleButtons = document.querySelectorAll('.detalle-btn');

            detalleButtons.forEach(function (button) {
                button.addEventListener('click', function () {
                    const proveedorId = button.getAttribute('data-id');

                    // Realizar una solicitud AJAX para obtener los detalles del proveedor
                    $.ajax({
                        url: '@Url.Action("Details", "Proveedores")/' + proveedorId,
                        type: 'GET',
                        success: function (data) {
                            // Mostrar los detalles en el modal
                            const detalleContent = `
                                                <p><strong>NIT:</strong> ${data.nitProveedor}</p>
                                                <p><strong>Nombre:</strong> ${data.nomProveedor}</p>
                                                <p><strong>Correo:</strong> ${data.correo}</p>
                                                <p><strong>Teléfono:</strong> ${data.telefono}</p>
                                                <p><strong>Dirección:</strong> ${data.direccion}</p>
                                            `;
                            document.getElementById('detalleContent').innerHTML = detalleContent;

                            // Mostrar el modal
                            $('#detalleModal').modal('show');
                        },
                        error: function () {
                            // Manejar errores si la solicitud AJAX falla
                            console.error('Error al obtener los detalles del proveedor.');
                        }
                    });
                });
            });
        });
    </script>
    <script>
        $(document).ready(function () {
            // Cierra el modal al hacer clic en el botón fuera del modal
            $('#closeModalBtn').on('click', function () {
                $('#detalleModal').modal('hide');
            });
        });
    </script>
}