Models/Servicio.cs
using EntreEspeciesNuevo.models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace EntreEspeciesNuevo.Models
{
    public partial class Servicio
    {
        public int IdServicio { get; set; }

        [Required(ErrorMessage = "El Nombre es Obligatorio*")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "El Nombre del Servicio debe tener entre 3 y 50 caracteres.")]
        public string NomServico { get; set; }

        [Required(ErrorMessage = "El Categoría es obligatorio*")]
        [RegularExpression("^(Belleza|Medicinal)$", ErrorMessage = "La Categoría debe ser 'Belleza' o 'Medicinal'.")]
        public string? Categoria { get; set; }

        [Required(ErrorMessage = "El Precio es Obligatorio*")]
        [Range(1000, 999999, ErrorMessage = "El Precio debe estar entre 1000 y 999999.")]
        public int? Precio { get; set; }

        public virtual ICollection<CitaInterna> CitaInternas { get; set; } = new List<CitaInterna>();

    }
}

Controllers/ServiciosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EntreEspeciesNuevo.Models;
using X.PagedList;

namespace EntreEspeciesNuevo.Controllers
{
    public class ServiciosController : Controller
    {
        private readonly EntreespeciessqlContext _context;

        public ServiciosController(EntreespeciessqlContext context)
        {
            _context = context;
        }

        // GET: Servicios
        public async Task<IActionResult> Index(int? page)
        {
            bool RegistrarServicios = await RegistrarServicio();
            ViewBag.RegistrarServicios = RegistrarServicios;
            bool EditarServicios = await EditarServicio();
            ViewBag.EditarServicios = EditarServicios;
            bool VerServicios = await VerServicio();
            ViewBag.VerServicios = VerServicios;
            bool BuscarServicios = await BuscarServicio();
            ViewBag.BuscarServicios = BuscarServicios;
            int pageSize = 99999;
            int pageNumber = page ?? 1;



            var servicios = await _context.Servicios.AsNoTracking().ToListAsync();

            var model = servicios.ToPagedList(pageNumber, pageSize);

            return View(model);
        }
        public async Task<bool> RegistrarServicio()
        {
            var username = User.Identity.Name;
            var usuario = await _context.Usuarios.FirstOrDefaultAsync(u => u.Nombre == username);
            if (usuario == null)
            {
                return false;
            }
            var configuracion = await _context.Configuracions
                .Where(c => c.IdRol == usuario.IdRol && c.IdPermiso == 35)
                .FirstOrDefaultAsync();
            return configuracion != null;
        }
        public async Task<bool> EditarServicio()
        {
            var username = User.Identity.Name;
            var usuario = await _context.Usuarios.FirstOrDefaultAsync(u => u.Nombre == username);
            if (usuario == null)
            {
                return false;
            }
            var configuracion = await _context.Configuracions
                .Where(c => c.IdRol == usuario.IdRol && c.IdPermiso == 36)
                .FirstOrDefaultAsync();
            return configuracion != null;
        }

        public async Task<bool> VerServicio()
        {
            var username = User.Identity.Name;
            var usuario = await _context.Usuarios.FirstOrDefaultAsync(u => u.Nombre == username);
            if (usuario == null)
            {
                return false;
            }
            var configuracion = await _context.Configuracions
                .Where(c => c.IdRol == usuario.IdRol && c.IdPermiso == 57)
                .FirstOrDefaultAsync();
            return configuracion != null;
        }
        public async Task<bool> BuscarServicio()
        {
            var username = User.Identity.Name;
            var usuario = await _context.Usuarios.FirstOrDefaultAsync(u => u.Nombre == username);
            if (usuario == null)
            {
                return false;
            }
            var configuracion = await _context.Configuracions
                .Where(c => c.IdRol == usuario.IdRol && c.IdPermiso == 39)
                .FirstOrDefaultAsync();
            return configuracion != null;
        }


        // GET: Servicios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Servicios == null)
            {
                return NotFound();
            }

            var servicio = await _context.Servicios
                .FirstOrDefaultAsync(m => m.IdServicio == id);
            if (servicio == null)
            {
                return NotFound();
            }

            return View(servicio);
        }

        // GET: Servicios/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Servicios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        // POST: Servicios/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdServicio,NomServico,Categoria,Precio")] Servicio servicio)
        {
            if (ModelState.IsValid)
            {
                // Verificar si ya existe un servicio con el mismo nombre
                if (_context.Servicios.Any(s => s.NomServico == servicio.NomServico))
                {
                    ModelState.AddModelError("NomServico", "Ya existe un servicio con este nombre.");
                    return RedirectToAction(nameof(Index));
                }

                _context.Add(servicio);
                await _context.SaveChangesAsync();

                // Devolver una respuesta JSON de éxito
                return RedirectToAction(nameof(Index));
            }

            // Si hay errores de validación, devolver una respuesta JSON con los errores
            var errors = ModelState.Values.SelectMany(v => v.Errors.Select(e => e.ErrorMessage));
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public IActionResult ValidarServicio(string nombre)
        {
            // Verificar si ya existe un cliente con el mismo número de documento
            bool existe = _context.Servicios.Any(s => s.NomServico == nombre);

            return Json(new { existe = existe });
        }

        // GET: Servicios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Servicios == null)
            {
                return NotFound();
            }

            var servicio = await _context.Servicios.FindAsync(id);
            if (servicio == null)
            {
                return NotFound();
            }
            return View(servicio);
        }
        [HttpGet]
        public IActionResult GetPrecioProducto(int servicioId)
        {
            try
            {
                var servicio = _context.Servicios.FirstOrDefault(s => s.IdServicio == servicioId);

                if (servicio != null)
                {
                    return Json(servicio.Precio);
                }

                return NotFound(); // O devuelve un valor predeterminado, según tus requisitos.
            }
            catch (Exception ex)
            {
                // Manejar la excepción según tus necesidades (por ejemplo, registrarla)
                return StatusCode(500, "Error interno del servidor");
            }
        }

        // POST: Servicios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdServicio,NomServico,Categoria,Precio")] Servicio servicio)
        {
            if (id != servicio.IdServicio)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(servicio);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ServicioExists(servicio.IdServicio))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(servicio);
        }

        // GET: Servicios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Servicios == null)
            {
                return NotFound();
            }

            var servicio = await _context.Servicios
                .FirstOrDefaultAsync(m => m.IdServicio == id);
            if (servicio == null)
            {
                return NotFound();
            }

            return View(servicio);
        }

        // POST: Servicios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Servicios == null)
            {
                return Problem("Entity set 'EntreespeciessqlContext.Servicios'  is null.");
            }
            var servicio = await _context.Servicios.FindAsync(id);
            if (servicio != null)
            {
                _context.Servicios.Remove(servicio);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ServicioExists(int id)
        {
          return (_context.Servicios?.Any(e => e.IdServicio == id)).GetValueOrDefault();
        }
    }
}

Views/Servicios/Create.cshtml
@model EntreEspeciesNuevo.Models.Servicio

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<head>
    <link rel="stylesheet" href="~/css/form.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-switch@3.3.4/dist/css/bootstrap3/bootstrap-switch.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400;700&display=swap">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Anta&family=Libre+Baskerville:ital,wght@0,400;0,700;1,400&display=swap" rel="stylesheet">
</head>
<div class="container">

    <div class="row">
        <div class="col-md-4 form-container">
            <center> <h4 class="card-title" style="font-family: Arial, sans-serif;">Crear Servicio</h4></center>
            <hr />
            <form asp-action="Create" id="form" >
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group">
                    <label asp-for="NomServico" class="control-label">Nombre Del Servicio:</label>
                    <input asp-for="NomServico"id="nombreServicio" class="form-control" oninput="validarDocumento(event)" />
                    <span asp-validation-for="NomServico" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Categoria" class="control-label">Categoría:</label>
                    <select asp-for="Categoria" class="form-control">
                        <option value="Belleza">Belleza</option>
                        <option value="Medicinal">Medicinal</option>
                    </select>
                    <span asp-validation-for="Categoria" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Precio" class="control-label">Precio:</label>
                    <input asp-for="Precio" class="form-control" type="text" oninput="validarPrecio(event)" />
                    <span asp-validation-for="Precio" class="text-danger"></span>
                </div>

                <div class="form-group text-center">
                    <input type="submit" value="Crear" class="btn btn-primary" />
                    <button type="button" onclick="window.location.href='@Url.Action("Index")'" class="btn btn-secondary btn-gray">Cancelar</button>
                </div>

            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>

        // Función para validar los campos antes de enviar el formulario
        $("#form").submit(function (event) {
            event.preventDefault(); // Evita que el formulario se envíe automáticamente

            // Realizar todas las validaciones de los campos
            if (!$(this).valid()) {
                // Si alguna validación falla, retornar false para evitar el envío del formulario
                return false;
            }

            // Validar el campo de documento antes de continuar
            validarServicio(function (nombreValido) {
                if (!nombreValido) {
                    // Si el documento no es válido, no se muestra la alerta de éxito y se detiene el envío del formulario
                    return false;
                }

                // Si el documento es válido, se procede a validar los demás campos
                if (!validarCampo('NomServico', 'Debe Ingresar Un Nombre')) return false;
                if (!validarCampo('Precio', 'Debe Ingresar Un Telefono')) return false;

                // Mostrar ventana de confirmación solo si todos los campos están llenos y correctos
                mostrarAlerta();
            });
        });
        // Función para validar el campo N° Documento
        function validarServicio(callback) {
            var nombre = document.getElementById("nombreServicio").value;
            if (!nombre) {
                Swal.fire({
                    icon: 'warning',
                    title: 'Por Favor Llene Los Campos',
                    text: 'Debe Ingresar Un Documento',
                    footer: 'Sistema de Información'
                });
                callback(false); // Indicar que la validación del documento falló
                return;
            }

            // Verificar en la base de datos si el documento ya existe
            $.ajax({
                url: '/Servicios/ValidarServicio',
                method: 'POST',
                data: { nombre: nombre },
                success: function (response) {
                    if (response.existe) {
                        Swal.fire({
                            icon: 'error',
                            title: 'Error',
                            text: 'El nombre ya está registrado',
                        });
                        callback(false); // Indicar que la validación del documento falló
                    } else {
                        callback(true); // Indicar que la validación del documento fue exitosa
                    }
                }
            });
        }

        // Función para mostrar una alerta de éxito y redirigir después de 3 segundos
        function mostrarAlerta() {
            Swal.fire({
                icon: 'success',
                title: 'Registro Exitoso',
                text: 'EL Servicio se registró correctamente.',
                footer: 'Sistema de Información',
                showConfirmButton: false
            });

            setTimeout(function () {
                // Envía el formulario una vez que se muestre el SweetAlert
                document.getElementById("form").submit();
            }, 3000);
        }

        // Función para validar los campos
        function validarCampo(nombreCampo, mensaje) {
            if ($("[name='" + nombreCampo + "']").val().trim().length < 1) {
                mostrarAlertaWarning(mensaje);
                return false;
            }
            return true;
        }

        // Función para mostrar una alerta de advertencia
        function mostrarAlertaWarning(mensaje) {
            Swal.fire({
                icon: 'warning',
                title: 'Por Favor Llene Los Campos',
                text: mensaje,
                footer: 'Sistema de Información'
            });
        }
        // Función para validar que solo se ingresen números en el campo Teléfono
        function validarPrecio(event) {
            const inputValue = event.target.value;

            if (isNaN(inputValue)) {
                event.target.value = inputValue.replace(/[^\d]/g, '');

                Swal.fire({
                    icon: 'error',
                    title: 'Carácter inválido',
                    text: 'Solo se permite ingresar números',
                    showConfirmButton: false,
                    timer: 1500
                });
            }
        }

        // Función para validar que solo se ingresen letras en el campo Nombre
        function validarNombreServicio(event) {
            const inputValue = event.target.value;

            if (/[^a-zA-ZñÑ\s]/.test(inputValue)) {
                event.target.value = inputValue.replace(/[^a-zA-ZñÑ\s]/g, '');

                Swal.fire({
                    icon: 'error',
                    title: 'Carácter inválido',
                    text: 'Solo se permite ingresar letras',
                    showConfirmButton: false,
                    timer: 1500
                });
            }
        }
    </script>

}

Views/Servicios/Delete.cshtml
@model EntreEspeciesNuevo.Models.Servicio

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Servicio</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NomServico)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NomServico)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Categoria)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Categoria)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Precio)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdServicio" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Servicios/Details.cshtml
@model EntreEspeciesNuevo.Models.Servicio

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    body{
        display:flex;
    }
</style>
<h1>Detalle</h1>

<div>
    <h4>Servicio</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Nombre del Servicio
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NomServico)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Categoria)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Categoria)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Precio)
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-info " asp-action="Edit" asp-route-id="@Model?.IdServicio">Editar</a> |
    <a class="btn btn-cancel" asp-action="Index">Regresar</a>
</div>

Views/Servicios/Edit.cshtml
@model EntreEspeciesNuevo.Models.Servicio

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<head>
    <link rel="stylesheet" href="~/css/form.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-switch@3.3.4/dist/css/bootstrap3/bootstrap-switch.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400;700&display=swap">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Anta&family=Libre+Baskerville:ital,wght@0,400;0,700;1,400&display=swap" rel="stylesheet">
</head>

<div class="row">
    <div class="col-md-4 form-container">
        <center> <h4 class="card-title" style="font-family: Arial, sans-serif;">Editar Servicio</h4></center>
        <hr />
        <form asp-action="Edit" id="editForm">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdServicio" />
            <div class="form-group">
                <label asp-for="NomServico" class="control-label">Nombre Del Servicio:<span style="color: red">*</span></label>
                <input asp-for="NomServico" class="form-control" readonly/>
                <span asp-validation-for="NomServico" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Categoria" class="control-label">Categoría:<span style="color: red">*</span></label>
                <input asp-for="Categoria" class="form-control" />
                <span asp-validation-for="Categoria" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Precio" class="control-label">Precio:<span style="color: red">*</span></label>
                <input asp-for="Precio" class="form-control" type="text" oninput="validarPrecio(event)" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
                <a class="btn btn-secondary" asp-action="Index">Cancelar</a>
            </div>
         
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <script>

        $(document).ready(function () {
            // Intercepta el envío del formulario
            $('#editForm').submit(function (event) {
                event.preventDefault(); // Previene el envío normal del formulario
                // Realizar todas las validaciones de los campos
                if (!$(this).valid()) {
                    // Si alguna validación falla, retornar false para evitar el envío del formulario
                    return false;
                }

                // Si el documento es válido, se procede a validar los demás campos
                if (!validarCampo('Precio', 'Debe Ingresar Un Precio')) return false;

                // Realiza la solicitud AJAX
                $.ajax({
                    url: '@Url.Action("Edit", "Servicios")',
                    type: 'POST',
                    data: $('#editForm').serialize(),
                    success: function (result) {
                        // Muestra la alerta de actualización exitosa
                        mostrarAlerta();
                    },
                    error: function (jqXHR, textStatus, errorThrown) {
                        console.error('Error en la solicitud AJAX:', textStatus, errorThrown);
                    }
                });
            });

            // Función para validar los campos
            function validarCampo(nombreCampo, mensaje) {
                if ($("[name='" + nombreCampo + "']").val().trim().length < 1) {
                    mostrarAlertaWarning(mensaje);
                    return false;
                }
                return true;
            }

            // Función para mostrar una alerta de advertencia
            function mostrarAlertaWarning(mensaje) {
                Swal.fire({
                    icon: 'warning',
                    title: 'Por Favor Llene Los Campos',
                    text: mensaje,
                    footer: 'Sistema de Información'
                });
            }

            // Función para mostrar una alerta de advertencia
            function mostrarAlertaError(mensaje) {
                Swal.fire({
                    icon: 'error',
                    title: 'Carácter inválido',
                    text: mensaje,
                });
            }

            // Función para mostrar una alerta de éxito
            function mostrarAlerta() {
                Swal.fire({
                    icon: 'success',
                    title: 'Actualización Exitosa',
                    text: 'El servicio se actualizó correctamente.',
                    footer: 'Sistema de Información',
                    showConfirmButton: false
                });

                setTimeout(function () {
                    window.location.href = '@Url.Action("Index", "Servicios")';
                }, 3000);
            }

            // Validación en tiempo real del campo Teléfono
            $('#Precio').on('input', function (event) {
                const inputValue = event.target.value;
                if (isNaN(inputValue)) {
                    event.target.value = inputValue.replace(/[^\d]/g, '');
                    mostrarAlertaError('Solo se permite ingresar números');
                }
            });

            // Validación en tiempo real del campo Nombre
            $('#NombreCliente').on('input', function (event) {
                const inputValue = event.target.value;
                if (/[^a-zA-ZñÑ\s]/.test(inputValue)) {
                    event.target.value = inputValue.replace(/[^a-zA-ZñÑ\s]/g, '');
                    mostrarAlertaError('Solo se permite ingresar letras');
                }
            });
        });
    </script>
}

Views/Servicios/Index.cshtml
@using X.PagedList.Mvc.Core;
@model X.PagedList.IPagedList<EntreEspeciesNuevo.Models.Servicio>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    var RegistrarServicios = ViewBag.RegistrarServicios;
    var EditarServicios = ViewBag.EditarServicios;
    var BuscarServicios = ViewBag.BuscarServicios;
    var VerServicios = ViewBag.VerServicios;
}
@if(VerServicios){
<head>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.css">
</head>

<head>
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-switch@3.3.4/dist/css/bootstrap3/bootstrap-switch.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400;700&display=swap">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Anta&family=Libre+Baskerville:ital,wght@0,400;0,700;1,400&display=swap" rel="stylesheet">
</head>


<div class="d-flex justify-content-between align-items-center">
    <h1>Servicios</h1>
        @if (RegistrarServicios)
        {
            <p>
                <a class="btn btn-primary" asp-action="Create" style="margin-right: 20px;">Crear Servicio</a>
            </p>
        }
    </div>

<div class="table-container">
    <table class="table">
        <thead>
            <tr>
                <th>
                    Nombre
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.First().Categoria)
                </th>
                <th>
                    Precio
                </th>
                <th>
                    Acciones
                </th>

            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.NomServico)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Categoria)
                    </td>
                    <td>                        
                        @("$ " + string.Format("{0:#,##0.00}", item.Precio))
                        @* @Html.DisplayFor(modelItem => item.Precio) *@
                    </td>

                    @if (EditarServicios)
                    {
                        <td>
                            <a class="btn btn-primary" asp-action="Edit" asp-route-id="@item.IdServicio">Editar</a>
                        </td>
                    }
                </tr>
            }
        </tbody>
    </table>
</div>
}
@section Scripts {
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.css">
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.js"></script>
    <script>
        $(document).ready(function () {
            $('.table').DataTable({
                "language": {
                    "sProcessing": "Procesando...",
                    "sLengthMenu": "Mostrar _MENU_ registros",
                    "sZeroRecords": "No se encontraron resultados",
                    "sEmptyTable": "Ningún dato disponible en esta tabla",
                    "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                    "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                    "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                    "sInfoPostFix": "",
                    "sSearch": "Buscar:",
                    "sUrl": "",
                    "sInfoThousands": ",",
                    "sLoadingRecords": "Cargando...",
                    "oPaginate": {
                        "sFirst": "Primero",
                        "sLast": "Último",
                        "sNext": "Siguiente",
                        "sPrevious": "Anterior"
                    },
                    "oAria": {
                        "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                        "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                    }
                },
                "lengthMenu": [4, 6, 10, 15],
                "pageLength": 10, // Número predeterminado de elementos por página
                "search": {
                    "search": "",
                    "searchPlaceholder": "Buscar...",
                },
                "dom": '<"d-flex justify-content-between align-items-center"lf>t<"d-flex justify-content-between align-items-center"ip>',
                "initComplete": function (settings, json) {
                    $('.dataTables_filter input[type="search"]').css({ 'border-radius': '5px', 'padding-left': '10px' });
                }
            });
        });
    </script>
}