Models/AccesoViewModels.cs
using System.ComponentModel.DataAnnotations;

namespace EntreEspeciesNuevo.Models
{
    public class AccesoViewModels
    {
        public class OlvidoContraseñaViewModel
        {
            [Required(ErrorMessage = "El campo correo es obligatorio.")]
            [EmailAddress(ErrorMessage = "Por favor, ingresa un correo electrónico válido.")]
            public string Correo { get; set; }
        }
    }
}

Models/ResetPassword.cs
using System.ComponentModel.DataAnnotations;

namespace EntreEspeciesNuevo.Models
{
    public class ResetPassword
    {
        public string Token { get; set; }
        //[Required(ErrorMessage = "La Contraseña es Obligatoria*")]
        [StringLength(50, MinimumLength = 8, ErrorMessage = "La Contraseña debe tener entre 8 y 50 caracteres")]
        [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^\da-zA-Z]).{8,50}$", ErrorMessage = "La Contraseña debe tener entre 8 y 50 caracteres al menos una letra mayúscula, una minúscula, un número y un carácter especial")]
        public string NuevaContraseña { get; set; }
        
    }
}

Controllers/AccesoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using EntreEspeciesNuevo.Models;
using Microsoft.AspNetCore.Authorization;
using System.Net.Mail;
using System.Net;
using Microsoft.CodeAnalysis.Scripting;

namespace EntreEspeciesNuevo.Controllers
{
    public class AccesoController : Controller
    {
        private readonly EntreespeciessqlContext _context;

        public AccesoController(EntreespeciessqlContext context)
        {
            _context = context;
        }

        // GET: Acceso/Index
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Index(string correo, string contraseña)
        {
            bool RecuperarContraseñas = await RecuperarContraseña();
            ViewBag.RecuperarContraseñas = RecuperarContraseñas;


            if (string.IsNullOrEmpty(correo) || string.IsNullOrEmpty(contraseña))
            {
                ModelState.AddModelError(string.Empty, "Correo y contraseña son obligatorios.");
                return View();
            }

            var hashedPassword = HashHelper.HashPassword(contraseña);
            var usuario = await _context.Usuarios.FirstOrDefaultAsync(u => u.Correo == correo && u.Contraseña == hashedPassword);

            if (usuario == null)
            {
                ModelState.AddModelError(string.Empty, "Correo o contraseña incorrectos.");
                return View();
            }

            if (usuario.Estado == "Inactivo")
            {
                ModelState.AddModelError(string.Empty, "Tu cuenta está inactiva. Porque a Luis Mario le dio la gana de Inactivarla.");
                return View();
            }

            // Crear identidad y establecer la cookie de autenticación
            var claims = new[] { new Claim(ClaimTypes.Name, usuario.Nombre) };
            var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
            var authProperties = new AuthenticationProperties
            {
                IsPersistent = true, // Puedes ajustar esto según tus necesidades
            };

            await HttpContext.SignInAsync(
                CookieAuthenticationDefaults.AuthenticationScheme,
                new ClaimsPrincipal(claimsIdentity),
                authProperties);

            return RedirectToAction("Index", "Home"); // Redirigir solo si la autenticación es exitosa
        }


        public async Task<bool> RecuperarContraseña()
        {
            var username = User.Identity.Name;
            var usuario = await _context.Usuarios.FirstOrDefaultAsync(u => u.Nombre == username);
            if (usuario == null)
            {
                return false;
            }
            var configuracion = await _context.Configuracions
                .Where(c => c.IdRol == usuario.IdRol && c.IdPermiso == 2)
                .FirstOrDefaultAsync();
            return configuracion != null;
        }



        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> VerClientes()
        {
            bool tieneAcceso = await VerCliente();
            return Json(new { accesoClientes = tieneAcceso });
        }
        public async Task<IActionResult> VisualizarMascotas()
        {
            bool tieneAcceso = await VisualizarMascota();
            return Json(new { accesoClientes = tieneAcceso });
        }
        public async Task<IActionResult> VisualizarUsuarios()
        {
            bool tieneAcceso = await VisualizarUsuario();
            return Json(new { accesoClientes = tieneAcceso });
        }
        public async Task<IActionResult> VisualizarCitas()
        {
            bool tieneAcceso = await VisualizarCita();
            return Json(new { accesoClientes = tieneAcceso });
        }
        public async Task<IActionResult> VisualizarCategorias()
        {
            bool tieneAcceso = await VisualizarCategoria();
            return Json(new { accesoClientes = tieneAcceso });
        }

        public async Task<IActionResult> VisualizarVentas()
        {
            bool tieneAcceso = await VisualizarVenta();
            return Json(new { accesoClientes = tieneAcceso });
        }
        public async Task<IActionResult> VisualizarCompras()
        {
            bool tieneAcceso = await VisualizarCompra();
            return Json(new { accesoClientes = tieneAcceso });
        }
        public async Task<IActionResult> VisualizarConfiguraciones()
        {
            bool tieneAcceso = await VisualizarConfiguracion();
            return Json(new { accesoClientes = tieneAcceso });
        }
        public async Task<IActionResult> VisualizarProveedores()
        {
            bool tieneAcceso = await VisualizarProveedor();
            return Json(new { accesoClientes = tieneAcceso });
        }
        public async Task<IActionResult> VisualizarProductos()
        {
            bool tieneAcceso = await VisualizarProducto();
            return Json(new { accesoClientes = tieneAcceso });
        }
        public async Task<IActionResult> VisualizarServicios()
        {
            bool tieneAcceso = await VisualizarServicio();
            return Json(new { accesoClientes = tieneAcceso });
        }
        public async Task<bool> VerCliente()
        {
            // Obtén el nombre de usuario desde la sesión
            var username = User.Identity.Name;

            // Obtén el usuario a partir del nombre de usuario
            var usuario = await _context.Usuarios.FirstOrDefaultAsync(u => u.Nombre == username);

            if (usuario == null)
            {
                // Puedes manejar esta situación según tus necesidades, por ejemplo, lanzar una excepción.
                return false;
            }

            // Verifica si el usuario tiene acceso según la configuración
            var configuracion = await _context.Configuracions
                .Where(c => c.IdRol == usuario.IdRol && c.IdPermiso == 23)
                .FirstOrDefaultAsync();

            return configuracion != null;
        }
        public async Task<bool> VisualizarUsuario()
        {
            // Obtén el nombre de usuario desde la sesión
            var username = User.Identity.Name;

            // Obtén el usuario a partir del nombre de usuario
            var usuario = await _context.Usuarios.FirstOrDefaultAsync(u => u.Nombre == username);

            if (usuario == null)
            {
                // Puedes manejar esta situación según tus necesidades, por ejemplo, lanzar una excepción.
                return false;
            }

            // Verifica si el usuario tiene acceso según la configuración
            var configuracion = await _context.Configuracions
                .Where(c => c.IdRol == usuario.IdRol && c.IdPermiso == 6)
                .FirstOrDefaultAsync();

            return configuracion != null;
        }
        public async Task<bool> VisualizarProducto()
        {
            // Obtén el nombre de usuario desde la sesión
            var username = User.Identity.Name;

            // Obtén el usuario a partir del nombre de usuario
            var usuario = await _context.Usuarios.FirstOrDefaultAsync(u => u.Nombre == username);

            if (usuario == null)
            {
                // Puedes manejar esta situación según tus necesidades, por ejemplo, lanzar una excepción.
                return false;
            }

            // Verifica si el usuario tiene acceso según la configuración
            var configuracion = await _context.Configuracions
                .Where(c => c.IdRol == usuario.IdRol && c.IdPermiso == 56)
                .FirstOrDefaultAsync();

            return configuracion != null;
        }
        public async Task<bool> VisualizarProveedor()
        {
            // Obtén el nombre de usuario desde la sesión
            var username = User.Identity.Name;

            // Obtén el usuario a partir del nombre de usuario
            var usuario = await _context.Usuarios.FirstOrDefaultAsync(u => u.Nombre == username);

            if (usuario == null)
            {
                // Puedes manejar esta situación según tus necesidades, por ejemplo, lanzar una excepción.
                return false;
            }

            // Verifica si el usuario tiene acceso según la configuración
            var configuracion = await _context.Configuracions
                .Where(c => c.IdRol == usuario.IdRol && c.IdPermiso == 28)
                .FirstOrDefaultAsync();

            return configuracion != null;
        }
        public async Task<bool> VisualizarCategoria()
        {
            // Obtén el nombre de usuario desde la sesión
            var username = User.Identity.Name;

            // Obtén el usuario a partir del nombre de usuario
            var usuario = await _context.Usuarios.FirstOrDefaultAsync(u => u.Nombre == username);

            if (usuario == null)
            {
                // Puedes manejar esta situación según tus necesidades, por ejemplo, lanzar una excepción.
                return false;
            }

            // Verifica si el usuario tiene acceso según la configuración
            var configuracion = await _context.Configuracions
                .Where(c => c.IdRol == usuario.IdRol && c.IdPermiso == 52)
                .FirstOrDefaultAsync();

            return configuracion != null;
        }
        public async Task<bool> VisualizarCita()
        {
            // Obtén el nombre de usuario desde la sesión
            var username = User.Identity.Name;

            // Obtén el usuario a partir del nombre de usuario

Views/Acceso/Index.cshtml
@{
    ViewData["Title"] = "Inicio de Sesión";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    body {
        background-image: url('/images/logipa.png');
        background-repeat: no-repeat;
        background-size: cover;
        margin: 0;
        display: flex;
        align-items: center;
        justify-content: center;
        height: 100vh;
        margin-right: 120px;
    }

    .container {
        margin-top: 50px;
    }

    .form-container {
        background-color: rgba(255, 255, 255, 0.8);
        padding: 20px;
        border: 2px solid #007BFF;
        border-radius: 10px;
        max-width: 400px;
    }

    .form-group {
        margin-bottom: 15px;
    }

    .form-control {
        width: 100%;
    }

    .btn-primary {
        background-color: #007BFF;
        border-color: #007BFF;
    }

        .btn-primary:hover {
            background-color: #0056b3;
            border-color: #0056b3;
        }

    .center-btn {
        text-align: center;
    }
</style>
@{
    var RecuperarContraseñas = ViewBag.RecuperarContraseñas;

}
<div class="container text-center mt-5">
    @if (ViewData.ModelState["correo"] != null && ViewData.ModelState["correo"].Errors.Count > 0)
    {
        <p class="text-danger">@Html.ValidationMessage("correo")</p>
    }
    
    @if (ViewData.ModelState["contraseña"] != null && ViewData.ModelState["contraseña"].Errors.Count > 0)
    {
        <p class="text-danger">@Html.ValidationMessage("contraseña")</p>
    }

    <div class="row">
        <div class="col-md-6">
            <img src="~/images/logor.png" width="400px" alt="Logo" class="img-fluid">
        </div>
        <div class="col-md-6 form-container">
            <form class="mb-4" method="post" asp-action="Index" asp-controller="Acceso" onsubmit="return validateForm()">
                <h1 class="mb-4">Iniciar Sesión</h1>

                <div class="form-group">
                    <label for="correo">Correo:</label>
                    <input type="text" class="form-control" id="correo" name="correo" />
                </div>
                <div class="form-group">
                    <label for="contraseña">Contraseña:</label>
                    <input type="password" class="form-control" id="contraseña" name="contraseña" />
                </div>
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <button type="submit" class="btn btn-primary">Iniciar Sesión</button><br />

                    <a class="text-info" href="@Url.Action("OlvidoContraseña", "Acceso")">¿Olvidaste tu contraseña?</a>

            </form>
        </div>
    </div>
</div>

<script>
    function validateForm() {
        // Verifica si los campos de correo y contraseña están vacíos y muestra SweetAlert
        var correoIsEmpty = document.getElementById("correo").value.trim() === "";
        var contraseñaIsEmpty = document.getElementById("contraseña").value.trim() === "";

        if (correoIsEmpty || contraseñaIsEmpty) {
            Swal.fire({
                icon: 'error',
                title: 'Error',
                text: 'Por favor, complete ambos campos.'
            });
            return false; // Evita que el formulario se envíe si hay campos vacíos
        }

        return true; // Permite que el formulario se envíe si la validación es exitosa
    }
</script>

Views/Acceso/OlvidoContraseña.cshtml
@model EntreEspeciesNuevo.Models.AccesoViewModels.OlvidoContraseñaViewModel
<style>
    body {
        background-image: url('/images/fondo.png');
        background-repeat: no-repeat;
        background-size: cover;
    }

    .container {
        margin-top: 50px;
    }

    .form-container {
        background-color: rgba(255, 255, 255, 0.8);
        padding: 20px;
        border: 2px solid #007BFF;
        border-radius: 10px;
        margin: 0 auto;
        max-width: 400px;
    }

    .form-group {
        margin-bottom: 15px;
    }

    .form-control {
        width: 100%;
    }

    .btn-primary {
        background-color: #007BFF;
        border-color: #007BFF;
    }

        .btn-primary:hover {
            background-color: #0056b3;
            border-color: #0056b3;
        }

    .center-btn {
        text-align: center;
    }
</style>
@{
    ViewData["Title"] = "Recuperar Contraseña";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container text-center mt-5">
    <h1 class="mb-4">Cambiar Contraseña</h1>
    <div class="row">
        <div class="col-md-4 form-container">
            @if (TempData["Mensaje"] != null)
            {
                <div class="alert alert-success">@TempData["Mensaje"]</div>
            }

            <form asp-action="OlvidoContraseña" asp-controller="Acceso" method="post">
                @Html.AntiForgeryToken()

                <div class="form-group">
                    <label asp-for="Correo"></label>
                    <input asp-for="Correo" class="form-control" />
                    <span asp-validation-for="Correo" class="text-danger"></span>
                </div>

                <button type="submit" class="btn btn-primary">Enviar Enlace</button>
                <a class="btn btn-secondary" href="@Url.Action("Index", "Acceso")">Regresar</a>
            </form>
        </div>
    </div>
    
</div>

Views/Acceso/ResetPassword.cshtml
@model ResetPassword

@{
    ViewData["Title"] = "Restablecimiento de Contraseña";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    body {
        background-image: url('/images/logipa.png');
        background-repeat: no-repeat;
        background-size: cover;
        margin: 0;
        display: flex;
        align-items: center;
        justify-content: center;
        height: 100vh;
        margin-right: 120px;
    }

    .container {
        margin-top: 50px;
    }

    .form-container {
        background-color: rgba(255, 255, 255, 0.8);
        padding: 20px;
        border: 2px solid #007BFF;
        border-radius: 10px;
        max-width: 400px;
    }

    .form-group {
        margin-bottom: 15px;
    }

    .form-control {
        width: 100%;
    }

    .btn-primary {
        background-color: #007BFF;
        border-color: #007BFF;
    }

        .btn-primary:hover {
            background-color: #0056b3;
            border-color: #0056b3;
        }

    .center-btn {
        text-align: center;
    }
</style>

<head>
    <link rel="stylesheet" href="~/css/form.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-switch@3.3.4/dist/css/bootstrap3/bootstrap-switch.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400;700&display=swap">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Anta&family=Libre+Baskerville:ital,wght@0,400;0,700;1,400&display=swap" rel="stylesheet">
</head>
<center>
<div class="container text-center mt-5">
    <div class="row">
            <div class="col-md-4 form-container" style="margin-left: 350px;">
            <center> <h4 class="card-title" style="font-family: Arial, sans-serif;">Restablecimiento de contraseña</h4></center>
            <hr />
            <form id="resetPasswordForm" method="post" asp-action="ResetPassword" asp-controller="Acceso" data-ajax="true" data-ajax-method="POST" class="form-horizontal">
                <div asp-validation-summary="All" class="text-danger"></div>
                <input type="hidden" asp-for="Token" />
               
                <div class="form-group">
                    <label asp-for="NuevaContraseña" class="control-label">Nueva Contraseña:</label>
                    <input class="form-control" type="password" asp-for="NuevaContraseña" required />
                </div>
                <div>
                    @* <button class="btn btn-succes" type="submit">Restablecer Contraseña</button> *@
                    <input type="submit" value="Restablecer" class="btn btn-primary" />
                </div>
            </form>            
        </div>
    </div>  
</div>
</center>